version: "3"

services:
  api:
    container_name: django-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - ./admin:/project/admin
    env_file:
      - .env
    
  database_pg13:
    container_name: pg13_database
    image: "postgres:13" # use latest official postgres version
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data/postgres/db-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - 5432:5432